### ISSUE TITLE
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous

### ISSUE THREAD

**Issue by wzhiyan** [KimHanjung/VISAGE#1]
Hi, Hanjung Kim,
Thanks for your excellent work and code!

When I train the model with configs/youtubevis_2019/visage_R50_bs16.yaml
I got the error such as :
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/wangs/anaconda3/envs/dvis/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/wangs/anaconda3/envs/dvis/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 28, in fetch
    data.append(next(self.dataset_iter))
  File "/home/wangs/anaconda3/envs/dvis/lib/python3.7/site-packages/detectron2/data/common.py", line 201, in __iter__
    yield self.dataset[idx]
  File "/media/VISAGE-main/visage/data_video/dataset_mapper.py", line 588, in __getitem__
    data = self._map_func(self._dataset[cur_idx], self._dataset[sample_idx])
  File "/home/wangs/anaconda3/envs/dvis/lib/python3.7/site-packages/detectron2/utils/serialize.py", line 26, in __call__
    return self._obj(*args, **kwargs)
  File "/media/VISAGE-main/visage/data_video/dataset_mapper.py", line 492, in __call__
    iou_matrix = self.mask_iou_matrix(paste_masks, instances.gt_masks, mode='ioy')
  File "/media/VISAGE-main/visage/data_video/dataset_mapper.py", line 566, in mask_iou_matrix
    y = y.reshape(y.shape[0], -1).float()
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous

It seems to be caused by the use of 'EMPTY ANNOTATIONS'.  To run the code,  
1) I set DATALOADER: FILTER_EMPTY_ANNOTATIONS to be True. The resulting AP is 53.36.
or 2) Set INPUT: PSEUDO: COPY_PASTE to be FALSE. The resulting AP is 52.92.
The other settings like batchsize, MAX_ITER are the same as default.

Both above results are slower than the results in the paper (55.1/ YouTube-VIS 2019). 
What should I do to reproduce the results, do you have any suggestions? Thanks a lot.

**Comment by KimHanjung** [comment]
Thank you for your interest in our work!

Regarding your question, I discovered that the error was due to discarded parts remaining from additional augmentation that is no longer used. I have fixed this issue in the official code.

As for the performance, I recommend checking your environment. I primarily conduct experiments using Python 3.9 and Torch 1.13. You can evaluate the environment using our official weights, which are trained with default settings. Please note that performance may fluctuate due to the training objective function.
